name: Hello World

on:
  push:
    branches-ignore: ["main", "development"]

jobs:
  echo-cowsay:
    runs-on: ubuntu-latest

    steps:
      - name: Print "Hello World" in Bash
        run: echo "Hello World"

      - name: Hello World with CowSay
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ¡Hola Muuuuundo!
