name: "Pull Request Labeler"

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pull-request-label:
    runs-on: ubuntu-latest

    steps:
      - name: Add Pull Request Label
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
